- name: Show IP interface brief
  hosts: cisco_routers:cisco_switches
  gather_facts: no

  tasks:
    - name: Show interfaces
      ansible.netcommon.cli_command:
        command: show ip interface brief
      register: output

    - debug:
        var: output.stdout_lines
