[cisco_routers]
r1 ansible_host=10.0.0.1

[cisco_switches]
sw_access ansible_host=192.168.30.2
sw_core ansible_host=192.168.30.1

[cisco_firewalls]
asa ansible_host=172.16.0.1

[cisco:children]
cisco_routers
cisco_switches
cisco_firewalls

[cisco:vars]
ansible_user=admin
ansible_password=cisco
ansible_connection=network_cli

[cisco_routers:vars]
ansible_network_os=ios

[cisco_switches:vars]
ansible_network_os=ios

[cisco_firewalls:vars]
ansible_network_os=asa
